#!/bin/sh

if [ -e /etc/default/updatehub-grubenv ]; then
	. /etc/default/updatehub-grubenv
fi

# If it requires a mount path, check it first
if [ -n "$mount_path" ]; then 
	mount | grep -q "$mount_path" || exit 1
fi

active=`grub-editenv $grubenv list | grep "updatehub_active="`
if [ -z "$active" ]; then
    active="updatehub_active=0"
fi

echo "$active" | awk -F= '/updatehub_active=/ { print $2 }'
exit 0
